apiVersion: apps/v1
kind: Deployment
metadata:
  name: final_client
  labels:
    app: final_client
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: final_client
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: final_client
    spec:
      containers:
      - image: huangx78/final_client:latest
        imagePullPolicy: Always
        name: final_client
        ports:
        - containerPort: 3000
          protocol: TCP