apiVersion: apps/v1
kind: Deployment
metadata:
  name: final-client-deployment
  #labels:
  #  app: final_client
  #namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: final-client
  #strategy:
  #  rollingUpdate:
  #    maxSurge: 25%
  #    maxUnavailable: 25%
  #  type: RollingUpdate
  template:
    metadata:
      labels:
        app: final-client
    spec:
      containers:
      - image: docker.io/huangx78/final_client:latest
        #imagePullPolicy: Always
        name: final-client-container
        ports:
        - containerPort: 3000
          #protocol: TCP