apiVersion: apps/v1
kind: Deployment
metadata:
  name: final-server
  labels:
    app: final-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: final-server
  #strategy:
  #  rollingUpdate:
  #    maxSurge: 25%
  #    maxUnavailable: 25%
  #  type: RollingUpdate
  template:
    metadata:
      labels:
        app: final-server
    spec:
      containers:
      - image: docker.io/huangx78/final_server:latest
        imagePullPolicy: Always
        name: final-server
        ports:
        - containerPort: 4000
          protocol: TCP